modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/tasgon/observable/issues"
authors = "tasgon"
license = "MPL"

[[mods]]
modId = "observable"
version = "${version}"
displayName = "Observable"
description = '''
See what's lagging your world.
'''

[[dependencies.observable]]
modId = "architectury"
type = "required"
versionRange = "[20.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.observable]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.observable]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

# [[dependencies.observable]]
# modId = "kotlinforforge"
# type = "required"
# versionRange = "[6.2,)"
# ordering = "AFTER"
# side = "BOTH"

[[mixins]]
config = "observable.common.json"
