plugins {
    id "com.gradleup.shadow" version "9.6.0"
    id "org.jetbrains.kotlin.jvm"
    id "me.shedaniel.unified-publishing"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

loom {
    runs {
        client {
            vmArg "-Xmx2G"
//            vmArg "-verbose:class"
//            vmArg "-Dmixin.debug=true"
        }
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    implementation "net.fabricmc:fabric-language-kotlin:${rootProject.fabric_language_kotlin_version}"
    implementation "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) {
        transitive = false
    }
    shadowCommon("org.jetbrains.kotlinx:kotlinx-serialization-protobuf-jvm:${rootProject.kotlin_serialization_version}") {
        transitive = false
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null

    relocate "kotlinx.serialization.protobuf", "observable.shadow.kotlinx.serialization.protobuf"
}

assemble.dependsOn shadowJar

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

// Credit to shedaniel (architectury) for most of this
unifiedPublishing {
    project {
        displayName = "$project.version (fabric)"
        releaseType = "$rootProject.release_channel"
        changelog = "See Observable's GitHub releases page for all changes between versions."
        gameVersions = ["$project.minecraft_version"]
        gameLoaders = ["fabric"]
        mainPublication shadowJar

        relations {
            depends {
                curseforge = "fabric-api"
                modrinth = "fabric-api"
            }
            depends {
                curseforge = "architectury-api"
                modrinth = "architectury-api"
            }
            depends {
                curseforge = "fabric-language-kotlin"
                modrinth = "fabric-language-kotlin"
            }
        }

        def curseApiKey = project.findProperty("CURSE_API_KEY") ?: System.getenv("CURSE_API_KEY")
        if (curseApiKey != null) {
            curseforge {
                token = curseApiKey
                id = rootProject.curseforge_id
                gameVersions.addAll "Java 25"
            }
        }

        def modrinthToken = project.findProperty("MODRINTH_TOKEN") ?: System.getenv("MODRINTH_TOKEN")
        if (modrinthToken != null) {
            modrinth {
                token = modrinthToken
                id = rootProject.modrinth_id
                version = "$project.version+$project.name"
            }
        }
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }
}
