import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    id "architectury-plugin" version "3.5-SNAPSHOT"
    id "dev.architectury.loom-no-remap" version "1.14-SNAPSHOT" apply false
    id "org.jetbrains.kotlin.jvm" version "2.4.10" apply false
    id "org.jetbrains.kotlin.plugin.serialization" version "2.4.10" apply false
    id "me.shedaniel.unified-publishing" version "0.1.+" apply false
    id "io.gitlab.arturbosch.detekt" version "1.23.8" apply false
    id "org.jlleitschuh.gradle.ktlint" version "14.2.0" apply false
    id "maven-publish"
}

subprojects {
    apply plugin: "dev.architectury.loom-no-remap"
    apply plugin: "org.jlleitschuh.gradle.ktlint"

    version = rootProject.mod_version
    group = rootProject.maven_group

    base {
        archivesName = rootProject.archives_base_name
    }

    java {
        withSourcesJar()
    }

    ktlint {
        additionalEditorconfig = ["ktlint_standard_no-wildcard-imports": "disabled"]
    }

    loom {
        silentMojangMappingsLicense()
        noIntermediateMappings()
    }

    repositories {
        mavenCentral()
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://thedarkcolour.github.io/KotlinForForge/" }
    }

    dependencies {
        minecraft("com.mojang:minecraft:${rootProject.minecraft_version}")
        implementation("org.jetbrains.kotlinx:kotlinx-serialization-protobuf:${rootProject.kotlin_serialization_version}")
        implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:${rootProject.kotlin_serialization_version}")
    }

    jar {
        from rootProject.file("LICENSE")
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }

    tasks.withType(KotlinCompilationTask).configureEach {
        compilerOptions.jvmTarget = JvmTarget.JVM_25
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    architectury {
        compileOnly()
    }

    repositories {
        mavenCentral()
        // Add repositories to retrieve artifacts from in here.
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        maven { url "https://maven.shedaniel.me" }
        maven { url "https://maven.architectury.dev" }
        maven { url "https://maven.terraformersmc.com/releases" }
        maven { url "https://jitpack.io" }
    }

    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }
}
