org.gradle.jvmargs=-Xmx6G

minecraft_version=26.1.2

archives_base_name=observable
mod_version=5.4.3
release_channel=beta
maven_group=observable

architectury_version=20.0.6

fabric_loader_version=0.19.2
fabric_api_version=0.150.0+26.1.2
fabric_language_kotlin_version=1.13.13+kotlin.2.4.10

neoforge_version=26.1.2.76
kotlin_for_forge_version=6.2.0

kotlin_serialization_version=1.11.0

curseforge_id=509575
modrinth_id=VYRu7qmG
