pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
    }
}

if (JavaVersion.current().ordinal() + 1 < 25) {
    throw new IllegalStateException("Please run Gradle with Java 25+!")
}

include("common")
include("fabric")
include("forge")

rootProject.name = "observable"
