plugins {
    id "com.gradleup.shadow" version "9.6.0"
    id "org.jetbrains.kotlin.jvm"
    id "me.shedaniel.unified-publishing"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    implementation "dev.architectury:architectury-neoforge:${rootProject.architectury_version}"
    implementation "thedarkcolour:kotlinforforge-neoforge:${rootProject.kotlin_for_forge_version}"

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) {
        transitive = false
    }
    shadowCommon("org.jetbrains.kotlinx:kotlinx-serialization-protobuf-jvm:${rootProject.kotlin_serialization_version}") {
        transitive = false
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    exclude "fabric.mod.json"
    exclude "**/*.kotlin_metadata"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null

    relocate "kotlinx.serialization.protobuf", "observable.shadow.kotlinx.serialization.protobuf"
}

assemble.dependsOn shadowJar

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

// Credit to shedaniel (architectury) for most of this
unifiedPublishing {
    project {
        displayName = "$project.version (neoforge)"
        releaseType = "$rootProject.release_channel"
        changelog = "See Observable's GitHub releases page for all changes between versions."
        gameVersions = ["$project.minecraft_version"]
        gameLoaders = ["neoforge"]
        mainPublication shadowJar

        relations {
            depends {
                curseforge = "architectury-api"
                modrinth = "architectury-api"
            }
            depends {
                curseforge = "kotlin-for-forge"
                modrinth = "kotlin-for-forge"
            }
        }

        var CURSE_API_KEY = project.findProperty("CURSE_API_KEY") ?: System.getenv("CURSE_API_KEY")
        if (CURSE_API_KEY != null) {
            curseforge {
                token = CURSE_API_KEY
                id = rootProject.curseforge_id
                gameVersions.addAll "Java 25"
            }
        }

        var MODRINTH_TOKEN = project.findProperty("MODRINTH_TOKEN") ?: System.getenv("MODRINTH_TOKEN")
        if (MODRINTH_TOKEN != null) {
            modrinth {
                token = MODRINTH_TOKEN
                id = rootProject.modrinth_id
                version = "$project.version+neoforge"
            }
        }
    }
}

publishing {
    publications {
        mavenNeoForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-neoforge"
            from components.java
        }
    }
}
